# Generated by Django 6.0 on 2025-12-30 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issuecategory_issueprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='issueimage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='issueprogress',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Issue Progress Updates'},
        ),
        migrations.AddField(
            model_name='issue',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the issue location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the issue location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, help_text='Address of the issue location in human-readable format e.g 123 Main St, Springfield', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='issues.issuecategory'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(help_text='User who reported this issue', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_resolved', 'is_archived', '-created_at'], name='issues_issu_is_reso_c0f0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=models.Index(fields=['issue', 'created_at'], name='issues_issu_issue_i_51c69b_idx'),
        ),
    ]
