# Generated by Django 6.0 on 2025-12-30 11:54

import django.db.models.deletion
import issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_options_alter_issueimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='IssueProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=issues.models.progress_image_upload_path)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='issues.issueprogress')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
