# Generated by Django 6.0 on 2025-12-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issue_address_alter_issue_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='general', max_length=100),
        ),
    ]
