# Generated by Django 6.0 on 2026-01-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_alter_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
