# Generated by Django 6.0 on 2026-01-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_alter_issue_latitude_alter_issue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
