# Generated by Django 6.0 on 2026-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_city_issue_resolved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=75, max_digits=175, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=75, max_digits=175, null=True),
        ),
    ]
